### ISSUE TITLE
Add Live! With Murray Franklin

### ISSUE THREAD

**Issue by HarleysTwin** [lynnandtonic/nestflix.fun#454] opened 2022-01-19 16:46 UTC
Please add as much of the following info as you can:

Title: Live! With Murray Franklin

Type (film/tv show): TV show - late night talk show

Film or show in which it appears: Joker

Is the parent film/show streaming anywhere? Yes - Amazon Prime

About when in the parent film/show does it appear? Sprinkled on TVs throughout; primary portion (not shown through a TV screen) is the third-to-last scene of the film.

Actual footage of the film/show can be seen (yes/no)? Yes; Here is a clip of the show's opening: https://www.youtube.com/watch?v=w4NrIYksNHA, and here is a clip of the Arthur Fleck interview: https://www.youtube.com/watch?v=TS3PG5m94dc.

Starring: Murray Franklin (host), Barry O'Donnell (co-host/announcer), and Ellis Drane and his Jazz Orchestra

Production Studio: NCB Studios 

Studio Location: Gotham City

"Fun" Fact: The final episode of the show aried in 1981, and had the guest line up of Lance Reynolds, Dr. Sally Friedman, and special guest, Arthur Fleck.  Fleck's failed standup routine at a comedy club caught the host's attention enough to invite him on the show.  Introducing Fleck as "Joker" at his request, Fleck's interview became increasingly morbid, with him admitting he was responsible for three unsolved murders on a subway car weeks earlier, culmitating into city riots.  The show ended not long after Fleck shoots Murray Franklin in the face, killing him on live TV.

**Comment by lynnandtonic** [comment] 2022-01-22 22:30
Thank you so much @HarleysTwin! This is a duplicate of #249 so closing this issue. This entry is in process now though!

**Closed by lynnandtonic** 2022-01-22 22:30 UTC
Labels: suggested title
