### ISSUE TITLE
Add Bumbie

### ISSUE THREAD

**Issue by ethanimation** [lynnandtonic/nestflix.fun#417] opened 2021-10-14 18:41 UTC
Please add as much of the following info as you can:

Title: Bumbie

Type (film/tv show): movie

Film or show in which it appears: Animaniacs Bumbi's Mom

Is the parent film/show streaming anywhere? HBO Max

About when in the parent film/show does it appear?  Animaniacs

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment] 2022-04-19 01:44
Duplicate of #231 so closing this one. Thank you!

**Closed by lynnandtonic** 2022-04-19 01:44 UTC
Labels: duplicate, suggested title

**Comment by lynnandtonic** [comment] 2022-04-20 16:16
Thank you! https://nestflix.fun/bumbie-the-dearest-deer/
