### ISSUE TITLE
Add [Legal Custodians]

### ISSUE THREAD

**Issue by duchyd** [lynnandtonic/nestflix.fun#436] opened 2021-12-14 17:50 UTC
Please add as much of the following info as you can:

Title: Legal Custodians

Type (film/tv show): tv show

Film or show in which it appears: Scrubs

Is the parent film/show streaming anywhere? Disney +

About when in the parent film/show does it appear? Scrubs S7 E10, My Waste of Time, 14:54 and 16:03

Actual footage of the film/show can be seen (yes/no)? yes

**Comment by lynnandtonic** [comment] 2022-01-23 20:07
Thank you @duchyd! This is a duplicate of #69 so I will close this one.

I’m still not sure I’m going to add this (because at least initially it is an imaginary thing), but still considering it!

**Closed by lynnandtonic** 2022-01-23 20:07 UTC
Labels: suggested title
