### ISSUE TITLE
The Careful Massacre of the Bourgeoisie

### ISSUE THREAD

**Issue by jjphantom** [lynnandtonic/nestflix.fun#195] opened 2021-08-15 22:50 UTC
Title: The Careful Massacre of the Bourgeoisie (1984)

Type (film/tv show): TV show

Film or show in which it appears: Mr Robot

Is the parent film/show streaming anywhere? Amazon Prime streaming

About when in the parent film/show does it appear?   eps2.2_init1.asec

Actual footage of the film/show can be seen (yes/no)? Yes

Tagline: It's New Year's Eve and an unexpected guest is SLASHING the party.

Cast:
No Cast Listings
Directed by "Douglas Carlton"

Misc
https://www.youtube.com/watch?v=l79cH9xEIng
https://www.imdb.com/title/tt8503138/
https://mrrobot.fandom.com/wiki/The_Careful_Massacre_of_the_Bourgeoisie

u rock

**Comment by lynnandtonic** [comment] 2021-08-16 03:50
Closing this as it’s a duplicate of #166. Thank you!

**Closed by lynnandtonic** 2021-08-16 03:51 UTC
