### ISSUE TITLE
Add “ The Johnny Karate Super Awesome Musical Explosion Show” from Parks and Recreation 

### ISSUE THREAD

**Issue by James-Rose-84** [lynnandtonic/nestflix.fun#151] opened 2021-08-14 00:45 UTC
![CDF8E407-7293-4000-B0E9-47BBF94C2EAB](https://user-images.githubusercontent.com/77655829/129429516-592f7694-0d73-473e-b173-909ee1781008.png)
![90A8A205-F715-4444-988E-80AAC3A49BD1](https://user-images.githubusercontent.com/77655829/129429518-1ea727c4-b858-4471-ba78-94db561f857e.jpeg)

**Comment by lynnandtonic** [comment] 2021-08-14 15:22
Hi @James-Rose-84! I’m going to close this issue because it’s a duplicate of #123 but be assured I have this on my list. Thank you!!

**Closed by lynnandtonic** 2021-08-14 15:22 UTC
