### ISSUE TITLE
Add: Love That Baby

### ISSUE THREAD

**Issue by TooniFNT** [lynnandtonic/nestflix.fun#295] opened 2021-08-18 00:28 UTC
Please add as much of the following info as you can:

**Title:** Love That Baby

**Type (film/tv show):** Sitcom

**Film or show in which it appears:** Batman: The Animated Series

**Is the parent film/show streaming anywhere?** HBO Max

**About when in the parent film/show does it appear?** In the episode "Baby-Doll", the titular villain was the star of this old sitcom.

**Actual footage of the film/show can be seen (yes/no)?** Yes.

**Comment by lynnandtonic** [comment] 2021-09-28 04:49
Thank you! This is a duplicate of #181 so going to close this one.

**Closed by lynnandtonic** 2021-09-28 04:49 UTC
Labels: suggested title
